### ISSUE TITLE
Removing auto scroll to page bottom

### ISSUE THREAD

**Issue by Serveurperso** [marekrei/encode-explorer#14]
I.E + Firefox : This is annoying for navigation since new version there is an auto scroll to page bottom for each new directory I open, no ergonomic.

I look the code and I found it : 
```
$('#user_name').focus();
```
What do you think to remove this line by default ?

**Comment by marekrei** [comment]
That does make sense, thanks for reporting it.

**Comment by Serveurperso** [comment]
Thanks;)
