### ISSUE TITLE
Sort issues

### ISSUE THREAD

**Issue by madsenfr** [marekrei/encode-explorer#31]
I found issues using your script with PHP 5.1.3 on free.fr.

Name weren't well sorted, so I fixed it line 2554 of version 6.4.1 in function sort by changing
	usort($this->files, "EncodeExplorer::cmp_".$this->sort_by);
with
	usort($this->files, array('EncodeExplorer','cmp_'.$this->sort_by));

Also size weren't sorted correctly according to the icon direction, so I fixed it line 2673 in function cmp_size by changing argument order.

Please see file in attachment 
[index_6.4.2.php.txt](https://github.com/marekrei/encode-explorer/files/75174/index_6.4.2.php.txt)

I also added midi audio file format at line 1481.

Hope it can help.

Regards.

**Comment by marekrei** [comment]
Thanks! Any chance you could formulate that as a pull request?

Also, do you know if your changes will affect other PHP versions? If they break the script for other users, then I won't be able to merge them.

**Comment by madsenfr** [comment]
Hi,

I just tested it on PHP 5.6.8 an it's ok.
As I don't add any new function, this should affect no other PHP version.

While testing on PHP 5.6.8 that is no more ISO-8859-1 by défault but UTF-8, I encoutered some issues with filename and dirname containing accented characters and had to replace htmlspecialchar with the following : 

	/* Convert ISO-8859-1 into HTML entities */
	function latinhtmlspecialchars($string){
		$convmap = array(0x80, 0xff, 0, 0xff);
		return mb_encode_numericentity($string, $convmap, "ISO-8859-1");
	}
I've done it only in my personal script.

**Comment by havet** [comment]
Hi,
maybe you can look into a similar problem: uploading of files beginning in the Swedish characters å, ä, ö ( a with a ring, a with trema= two dots and o with trema = two dots) loose the first letter when uploaded. I will add a separate issue.
