### ISSUE TITLE
Failed to upload the file! error when uploading

### ISSUE THREAD

**Issue by bochen415** [marekrei/encode-explorer#63]
System:
I'm running Debian Jessie x64
Linux *hostname* 3.16.0-4-amd64 # 1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
PHP 5.6.30-0+deb8u1
nginx/1.6.2
encode-explorer 6.4.1

What's wrong:
When trying to upload a file I get an error 
`Failed to upload the file!`

What it should be:
file should be uploaded

The changes I added to the file are just the config options like:
$_CONFIG['require_login'] = true;
$_CONFIG['users'] = array....;
$_CONFIG['delete_enable'] = true;
$_CONFIG['upload_reject_extension'] = array("php", "php2", "php3", "php4", "php5", "phtml", "exe");

I didn't touch
$_CONFIG['upload_allow_type'] = array();

Logs:
nginx error.log gives me:
`2017/03/18 21:43:39 [error] 8871#0: *29 FastCGI sent in stderr: "PHP message: PHP Warning:  finfo_file(): Empty filename or path in /var/www/repo/files.php on line 2407" while reading response header from upstream, client: X.X.X.X, server: my_subdomain, request: "POST /files.php?dir=directory/directory HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "my_subdomain", referrer: "https://my_subdomain/files.php?dir=directory/directory"`

The magic file is located on my system at `/usr/share/file/magic.mgc`
there's also a symlink to that file at `/usr/share/misc/magic.mgc`

Edit: it was a .zip file that failed.

**Comment by NewEraCracker** [comment]
How big was the file? Do smaller files work?

**Comment by bochen415** [comment]
Someone forgot to change upload_max_filesize in php.ini. By default it was 2MB max.
Yup.. sorry for the disturbance. Closing
