### ISSUE TITLE
imagelink

### ISSUE THREAD

**Issue by fred1265** [marekrei/encode-explorer#70]
When I click on picture is it shown. I like to see the foldername and filename an a back button. How can i do that?

**Comment by fred1265** [comment]
When i click an folder it is shown on top (breadcrum)
When i click on image. i like to see the full path with file and extension.
not the picture itself. Then i am be able to copy / past the url of my image for further use.

**Comment by borekon** [comment]
Right click on the link --> copy address (may vary depending on browser)

**Comment by fred1265** [comment]
Thanks, was thinking difficult.
