### ISSUE TITLE
How to use in nginx

### ISSUE THREAD

**Issue by mrlongshen** [marekrei/encode-explorer#73]
Anyone?
How to use this?

**Comment by c-rilaun** [comment]
"Gneugneugneu, how to use it, please help..."

You are not on google mate. If you have an issue, tell us, but we can't guess what your problem is.

I have a server with **php-fpm7.3 / nginx** & everything work **like a charm**.

**Comment by mrlongshen** [comment]
Thanks for your good response. Adios.
